// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTuhfiCzvjAbxdwZgY0fT4BdaNVcJ183A',
    appId: '1:494494776959:web:181094ff9714c746ce894a',
    messagingSenderId: '494494776959',
    projectId: 'learnity-27666',
    authDomain: 'learnity-27666.firebaseapp.com',
    storageBucket: 'learnity-27666.firebasestorage.app',
    measurementId: 'G-MMLQ3THHQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSO-A9FYZz5459F_LMBrODAsjLfctYt9U',
    appId: '1:494494776959:android:3ea85dc1fc0fa136ce894a',
    messagingSenderId: '494494776959',
    projectId: 'learnity-27666',
    storageBucket: 'learnity-27666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmEQ2XePXLazik4vg8EO7tGZopbziII9s',
    appId: '1:494494776959:ios:0842d912821dd606ce894a',
    messagingSenderId: '494494776959',
    projectId: 'learnity-27666',
    storageBucket: 'learnity-27666.firebasestorage.app',
    androidClientId: '494494776959-kt7hb4osalsafo0vqotvlb8vjt479eb0.apps.googleusercontent.com',
    iosClientId: '494494776959-obdm32o4qv2dnbkip266ric8cu7s1ap9.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmEQ2XePXLazik4vg8EO7tGZopbziII9s',
    appId: '1:494494776959:ios:0842d912821dd606ce894a',
    messagingSenderId: '494494776959',
    projectId: 'learnity-27666',
    storageBucket: 'learnity-27666.firebasestorage.app',
    androidClientId: '494494776959-kt7hb4osalsafo0vqotvlb8vjt479eb0.apps.googleusercontent.com',
    iosClientId: '494494776959-obdm32o4qv2dnbkip266ric8cu7s1ap9.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTuhfiCzvjAbxdwZgY0fT4BdaNVcJ183A',
    appId: '1:494494776959:web:6f0b83601f3fab52ce894a',
    messagingSenderId: '494494776959',
    projectId: 'learnity-27666',
    authDomain: 'learnity-27666.firebaseapp.com',
    storageBucket: 'learnity-27666.firebasestorage.app',
    measurementId: 'G-KQHE794SGN',
  );
}
